debianize

diff --git a/debian/init b/debian/init
--- a/debian/init
+++ b/debian/init
@@ -1,4 +1,5 @@
 #!/bin/sh
+
 ### BEGIN INIT INFO
 # Provides:          epv
 # Required-Start:    $remote_fs $syslog
@@ -12,11 +13,11 @@
 
 # Author: Aleksey Morarash <aleksey.morarash@gmail.com>
 
-PATH=/bin:/sbin:/usr/bin
+PATH=/sbin:/bin:/usr/bin
 DESC="Erlang Photo Viewer"
 NAME=epv
-DAEMON=/usr/bin/$NAME
-PIDFILE=/var/run/$NAME.pid
+DAEMON=/usr/bin/${NAME}-wrapper
+PIDFILE=/var/lib/$NAME/pid
 SCRIPTNAME=/etc/init.d/$NAME
 
 # Exit if the package is not installed
@@ -25,6 +26,7 @@ SCRIPTNAME=/etc/init.d/$NAME
 # Read configuration variable file if it is present
 [ -r /etc/default/$NAME ] && . /etc/default/$NAME
 
+# Generate command line for the daemon
 DAEMON_ARGS="$MEDIA_PATH $CACHE_PATH"
 [ -n "$LANGUAGE" ] && DAEMON_ARGS="-l $LANGUAGE $DAEMON_ARGS"
 [ -n "$BIND_ADDR" ] && DAEMON_ARGS="-i $BIND_ADDR $DAEMON_ARGS"
@@ -34,21 +36,31 @@ DAEMON_ARGS="$MEDIA_PATH $CACHE_PATH"
 [ -n "$LOG_PATH" ] && DAEMON_ARGS="--log $LOG_PATH $DAEMON_ARGS"
 [ -n "$LOGLEVEL" ] && DAEMON_ARGS="-v $LOGLEVEL $DAEMON_ARGS"
 
-[ -r /lib/init/vars.sh ] && . /lib/init/vars.sh
+# Load the VERBOSE setting and other rcS variables
+. /lib/init/vars.sh
+
+# Define LSB log_* functions.
+# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
+# and status_of_proc is working.
 . /lib/lsb/init-functions
 
+#
+# Function that starts the daemon/service
+#
 do_start() {
     # Return
     #   0 if daemon has been started
     #   1 if daemon was already running
     #   2 if daemon could not be started
-    start-stop-daemon --quiet --status \
-        --pidfile $PIDFILE --user $NAME && return 1
+    do_status && return 1
     start-stop-daemon --quiet --start --background --make-pidfile \
         --pidfile $PIDFILE --user $NAME --chuid $NAME \
         --exec $DAEMON -- $DAEMON_ARGS || return 2
 }
 
+#
+# Function that stops the daemon/service
+#
 do_stop() {
     # Return
     #   0 if daemon has been stopped
@@ -61,6 +73,18 @@ do_stop() {
     [ "$RETVAL" = 2 ] && return 2
     rm -f $PIDFILE
     return "$RETVAL"
+}
+
+#
+# Function that checks the daemon/service status
+#
+do_status(){
+    # Return
+    #   0 if program is running.
+    #   1 if program is not running and the pid file exists.
+    #   3 if program is not running.
+    #   4 unable to determine program status.
+    start-stop-daemon --quiet --status --pidfile $PIDFILE --user $NAME
 }
 
 case "$1" in
@@ -81,7 +105,16 @@ case "$1" in
         esac
         ;;
     status)
-        status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
+        do_status
+        RETVAL="$?"
+        if [ "$VERBOSE" != no ]; then
+            case "$RETVAL" in
+                0) log_success_msg "$DESC $NAME is running" ;;
+                1|3) log_failure_msg "$DESC $NAME is not running" ;;
+                4) log_failure_msg "$DESC $NAME: failed to get status" ;;
+            esac
+        fi
+        exit $RETVAL
         ;;
     restart|force-reload)
         log_daemon_msg "Restarting $DESC" "$NAME"
